services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - 8080:8080
    environment:
      - ENABLE_OLLAMA_API=False
      - ENABLE_OPENAI_API=True
      - OPENAI_API_BASE_URL=http://host.docker.internal:9090/api/v1
      - ENV=dev
      - WEBUI_AUTH=False
      - WEBUI_NAME=Kouign AI
    pull_policy: always
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
