spring:
  application:
    name: kouign
  threads:
    virtual:
      enabled: true
  ai:
    openai:
      base-url: http://localhost/ai/ollama
  mvc:
    apiversion:
      use:
        path-segment: 1
      default: 1.0
  web:
    error:
      include-message: always
      include-binding-errors: always
      include-stacktrace: always
      include-exception: true

kouign:
  models:
    - id: ker
      name: Ker
      created: 2024-05-13T00:00:00Z
      ownedBy: me
      baseModel: "qwen3-coder:30b"

server:
  port: 9090
  address: 0.0.0.0

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.web.servlet.mvc.method.annotation: DEBUG
    org.springframework.boot.web.servlet.error: DEBUG
    org.springframework.web.client: DEBUG
    org.springframework.http.client: DEBUG
    fr.spirylics.kouign: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
