spring:
  application:
    name: kouign
  threads:
    virtual:
      enabled: true
  mvc:
    apiversion:
      use:
        path-segment: 1
        media-type-parameter[application/json]=version:supported: 1.0
      default: 1.0

server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

kouign:
  models:
    - id: ker
      name: Ker
      created: 2024-05-13T00:00:00Z
      ownedBy: me
