spring:
  application:
    name: kouign
  threads:
    virtual:
      enabled: true
  ai:
    openai:
      base-url: http://localhost/ai/ollama
    mcp:
      client:
        enabled: true
        name: kouign-mcp-client
        version: 1.0.0
        request-timeout: 30s
        type: SYNC
        streamable-http:
          connections:
            context7:
              url: http://localhost
              endpoint: /context7/mcp
  mvc:
    apiversion:
      use:
        path-segment: 1
      default: 2.1.0
      supported:
        - 1.0.0
        - 2.0.0
        - 2.1.0
  web:
    error:
      include-message: always
      include-binding-errors: always
      include-stacktrace: always
      include-exception: true

kouign:
  models:
    ker:
      id: ker
      name: Ker
      created: 2024-05-13T00:00:00Z
      ownedBy: me
      baseModel: "qwen3-coder:30b"
  random-pause: "PT0.2S"

server:
  port: 9090
  address: 0.0.0.0

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.web.servlet.mvc.method.annotation: DEBUG
    org.springframework.boot.web.servlet.error: DEBUG
    org.springframework.web.client: DEBUG
    org.springframework.http.client: DEBUG
    fr.spirylics.kouign: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: '*'
    jmx:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  jmx:
    enabled: true
